// Full ~180-icon lucide-react mega-map for the admin category-icon picker.
// Admin-only: reachable exclusively through the lazy /admin route. Don't
// import this from public surfaces (Sidebar, PostAd) — see categoryIcons.tsx
// for the curated, eagerly-bundled subset those use.
import type { LucideIcon } from "lucide-react";
import {
    Gift,
    ShoppingBag,
    Laptop,
    Headphones,
    Bike,
    Tv,
    Monitor,
    Scissors,
    Hammer,
    Coffee,
    Wine,
    Pizza,
    Apple,
    Flower2,
    TreePine,
    Sun,
    Moon,
    Cloud,
    Umbrella,
    Snowflake,
    Flame,
    Droplet,
    Mountain,
    Building2,
    Store,
    School,
    Hotel,
    Church,
    Landmark,
    Factory,
    Warehouse,
    Tent,
    Rocket,
    Anchor,
    Ship,
    Train,
    Bus,
    Truck,
    Tractor,
    Ambulance,
    Stethoscope,
    Pill,
    Syringe,
    Activity,
    Microscope,
    GraduationCap,
    BookOpen,
    Library,
    Newspaper,
    FileText,
    Folder,
    MessageCircle,
    Mail,
    Phone,
    Wifi,
    Bluetooth,
    Battery,
    Zap,
    Lightbulb,
    Cpu,
    HardDrive,
    Mouse,
    Keyboard,
    Printer,
    Speaker,
    Radio,
    Mic,
    Video,
    Film,
    Image,
    Brush,
    Pen,
    Edit3,
    Type,
    Glasses,
    Crown,
    Medal,
    Trophy,
    Target,
    Flag,
    Star,
    Sparkles,
    Diamond,
    Gem,
    Coins,
    Banknote,
    CreditCard,
    Receipt,
    ShoppingCart,
    Package,
    Box,
    Archive,
    Trash2,
    Recycle,
    Leaf,
    Sprout,
    Bug,
    Cat,
    Dog,
    Bird,
    Fish,
    Egg,
    Bone,
    Footprints,
    HandMetal,
    ThumbsUp,
    Users,
    UserCircle,
    PersonStanding,
    Smile,
    Frown,
    Angry,
    PartyPopper,
    Cake,
    IceCream,
    Cookie,
    Candy,
    Soup,
    Salad,
    Beef,
    Croissant,
    Beer,
    Martini,
    Cigarette,
    Dna,
    Atom,
    Brain,
    Eye,
    Ear,
    Hand,
    Bed,
    Sofa,
    Lamp,
    Fan,
    AirVent,
    Refrigerator,
    WashingMachine,
    Microwave,
    CookingPot,
    UtensilsCrossed,
    Timer,
    AlarmClock,
    Clock,
    Calendar,
    CalendarDays,
    Map,
    MapPin,
    Compass,
    Navigation,
    Route,
    Signpost,
    Globe,
    Languages,
    QrCode,
    Barcode,
    Scan,
    Search,
    Filter,
    SlidersHorizontal,
    Settings,
    Cog,
    Axe,
    Shovel,
    Paintbrush,
    PaintRoller,
    Ruler,
    Eraser,
    Paperclip,
    Link,
    Lock,
    Unlock,
    Key,
    Shield,
    ShieldCheck,
    Fingerprint,
} from "lucide-react";
import { iconMap as curatedIconMap } from "./categoryIcons";

/**
 * Full map of available icon names to Lucide components (curated set + every
 * remaining icon offered by the admin picker). Icon names stored in the DB
 * should be PascalCase (e.g., "Car", "ShoppingBag").
 */
export const iconMap: Record<string, LucideIcon> = {
    ...curatedIconMap,
    Gift, ShoppingBag, Laptop, Headphones, Bike, Tv, Monitor, Scissors,
    Hammer, Coffee, Wine, Pizza, Apple, Flower2, TreePine, Sun, Moon, Cloud,
    Umbrella, Snowflake, Flame, Droplet, Mountain, Building2, Store, School,
    Hotel, Church, Landmark, Factory, Warehouse, Tent, Rocket, Anchor, Ship,
    Train, Bus, Truck, Tractor, Ambulance, Stethoscope, Pill, Syringe,
    Activity, Microscope, GraduationCap, BookOpen, Library, Newspaper,
    FileText, Folder, MessageCircle, Mail, Phone, Wifi, Bluetooth, Battery,
    Zap, Lightbulb, Cpu, HardDrive, Mouse, Keyboard, Printer, Speaker, Radio,
    Mic, Video, Film, Image, Brush, Pen, Edit3, Type, Glasses, Crown, Medal,
    Trophy, Target, Flag, Star, Sparkles, Diamond, Gem, Coins, Banknote,
    CreditCard, Receipt, ShoppingCart, Package, Box, Archive, Trash2, Recycle,
    Leaf, Sprout, Bug, Cat, Dog, Bird, Fish, Egg, Bone, Footprints, HandMetal,
    ThumbsUp, Users, UserCircle, PersonStanding, Smile, Frown, Angry,
    PartyPopper, Cake, IceCream, Cookie, Candy, Soup, Salad, Beef, Croissant,
    Beer, Martini, Cigarette, Dna, Atom, Brain, Eye, Ear, Hand, Bed, Sofa,
    Lamp, Fan, AirVent, Refrigerator, WashingMachine, Microwave, CookingPot,
    UtensilsCrossed, Timer, AlarmClock, Clock, Calendar, CalendarDays, Map, MapPin,
    Compass, Navigation, Route, Signpost, Globe, Languages, QrCode, Barcode,
    Scan, Search, Filter, SlidersHorizontal, Settings, Cog, Axe,
    Shovel, Paintbrush, PaintRoller, Ruler, Eraser, Paperclip, Link, Lock, Unlock,
    Key, Shield, ShieldCheck, Fingerprint,
};

/**
 * List of available icon names for the admin icon picker dropdown.
 */
export const AVAILABLE_ICONS = Object.keys(iconMap);
